version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - venv.env
    depends_on:
      - db
      - minio

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: files
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - test
    restart: always

volumes:
  minio_data:

networks:
  test:
 
